package wen.jianbao.model;

import com.jfinal.plugin.activerecord.Page;
import wen.jianbao.helper.ModelHelper;
import wen.jianbao.helper.sqlhelper.Paging;
import wen.jianbao.model.base.BaseBlog;

import javax.servlet.http.HttpServletRequest;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
    public static       String tableName = "blog";
    public static final Blog   dao       = new Blog().dao();

    /**
     * 根据 ID 获取信息
     *
     * @param id 记录ID
     * @return 文章记录
     */
    public Blog getInfoById(String id) {
        return new ModelHelper<Blog>(dao)
                .where("blogId", id)
                .findFirst(dao._getTable().getName());
    }

    /**
     * 获取列表
     *
     * @param where 条件
     * @param field 字段
     * @param order 排序
     * @param limit 显示记录数
     * @return 记录列表
     */
    public List<Blog> getList(String where, String field,
                              String order, int limit) {
        return new ModelHelper<Blog>(dao)
                .select(field)
                .from(tableName)
                .where(where)
                .findAll();
    }

    /**
     * 分页列表
     *
     * @param where      查询条件
     * @param field      显示字段
     * @param order      排序
     * @param pageNumber 当前分页数
     * @param pageSize   每页记录数
     * @return 分页对象
     */
    public Paging<Blog> getPageList(HttpServletRequest request, String where, String field,
                                    String order, int pageNumber, int... pageSize) {
        return new ModelHelper<Blog>(dao)
                .select(field)
                .from(tableName)
                .where(where)
                .orderBy(order)
                .findPaging(request, pageNumber, pageSize);
    }

    /**
     * 分页列表
     *
     * @param where      查询条件
     * @param field      显示字段
     * @param order      排序
     * @param pageNumber 当前分页数
     * @param pageSize   每页记录数
     * @return 分页对象
     */
    public Page<Blog> getPageList(String where, String field,
                                  String order, int pageNumber, int... pageSize) {
        return new ModelHelper<Blog>(dao)
                .select(field)
                .from(dao._getTable().getName())
                .where(where)
                .orderBy(order)
                .findPage(pageNumber, pageSize);
    }

    /**
     * 分页列表
     *
     * @param where      查询条件
     * @param field      显示字段
     * @param order      排序
     * @param pageNumber 当前分页数
     * @param pageSize   每页记录数
     * @return 分页对象
     */
    public Paging<Blog> getPageList(HttpServletRequest request, Map<String, Object> where, String field,
                                    String order, int pageNumber, int... pageSize) {
        return new ModelHelper<Blog>(dao)
                .select(field)
                .from(tableName)
                .where(where)
                .orderBy(order)
                .findPaging(request, pageNumber, pageSize);
    }

    /**
     * 分页列表
     *
     * @param where      查询条件
     * @param field      显示字段
     * @param order      排序
     * @param pageNumber 当前分页数
     * @param pageSize   每页记录数
     * @return 分页对象
     */
    public Page<Blog> getPageList(Map<String, Object> where, String field,
                                  String order, int pageNumber, int... pageSize) {
        return new ModelHelper<Blog>(dao)
                .select(field)
                .from(tableName)
                .where(where)
                .orderBy(order)
                .findPage(pageNumber, pageSize);
    }
}
